name: 'Tests'
inputs:
  swift-version:  # id of input
    description: 'Version of Swift to build with'
    required: true

runs:
    using: "composite"
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift-version }}
      - shell: bash
        run: swift --version
      - shell: bash
        run: swift run SincereAuthServer migrate -y --env test
      - shell: bash
        run: swift test
